### ISSUE TITLE
Please remove setuptools from install_requires

### ISSUE THREAD

**Issue by whardier** [best-doctor/flake8-variables-names#10]
Please remove `setuptools` from `install_requires` in `setup.py`.  When using tools that compile list of deployable packages setuptools will be inadvertantly included and when using well known tools like `pip-tools` to compile a requirements file with hashes it will inadvertantly issue a warning that including `setuptools` in the compiled requirements file is considered unsafe (chicken egg issue).

**Comment by korneevm** [comment]
Hi @whardier!

Thanks for the report! I've fixed it in 0.0.5
