### ISSUE TITLE
Allow `use-varnames-strict-mode` with a configuration option

### ISSUE THREAD

**Issue by stdedos** [best-doctor/flake8-variables-names#13]
**Is your feature request related to a problem? Please describe.**
When multiple execution contexts are defined (e.g. dev-env, pre-commit, CI), it will be nice to have a SSOT (https://en.wikipedia.org/wiki/Single_source_of_truth) of whether this option is enabled or not.

**Describe the solution you'd like**
"For all of flake8's configuration streams" (e.g. `.flake8`, `pyproject.toml`), I can set `use-varnames-strict-mode = true` on the file, and `flake8-variables-names` picks it up.

**Describe alternatives you've considered**
pre-commit has `args` to pass custom args to tools, but I cannot affect how the dev-env reacts to that.
e.g. developers IDE may not by-default activate that setting, and, even if the developer remembers to run manually on the terminal `flake8 --use-varnames-strict-mode`, s/he will still get no feedback while writing code.

**Additional context**

**Comment by Arondit** [comment]
Thank you very much for idea. We've created a task in our tracker. I don't know though, when we will be able to take it in work.

**Comment by PashaWNN** [comment]
I've done it here: https://github.com/best-doctor/flake8-variables-names/pull/16
Waiting for approval

**Comment by PashaWNN** [comment]
@Arondit merged. Check it out 😉

**Comment by Arondit** [comment]
@stdedos i've closed issue because it's done. If something is wrong, please, create new issue.
