### ISSUE TITLE
Error messages do not contain variable name

### ISSUE THREAD

**Issue by uhbif19** [best-doctor/flake8-variables-names#2]
`VNE002` error message looks like this:

```
./some/dirs/some_file.py:30:9: VNE002 variable name should be clarified
```

It would be easier to understand and group errors, if the error message included variable name, like this:

```
./some/dirs/some_file.py:30:9: VNE002 variable name 'some_var' should be clarified
```
This style is used by flake8:

```
./some/dirs/some_file.py:18:5: F841 local variable 'some_var' is assigned to but never used
```

Is static error message an intentional design decision?

**Comment by Melevir** [comment]
Yes, it would be nice to add variable name to error message.

**Comment by uhbif19** [comment]
@Melevir Okay, will try to do this on the holidays.

**Comment by uhbif19** [comment]
Then making PR, saw that short variable error VNE001 has the same problem.  Not sure about text for this error, though.

Did this: "VNE001 single letter variable names like 'a' are not allowed".

Now title of issue does not match PR, changed it.

**Comment by uhbif19** [comment]
InNow title does not match the PR. Changed it.
